# .pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# Python 파일 linting 및 포맷팅
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        files: \.py$

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
        files: \.py$

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        files: \.py$
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
        additional_dependencies: [flake8-bugbear]
        args:
        - --max-line-length=88
        - --extend-ignore=E203,W503

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        files: \.py$
        additional_dependencies: [types-requests, types-psycopg2]

# Jupyter 노트북 linting 및 포맷팅
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
    -   id: nbqa-black
        name: nbqa-black
        args: ["--line-length=88"]
    -   id: nbqa-isort
        name: nbqa-isort
        args: ["--profile=black"]
    -   id: nbqa-flake8
        name: nbqa-flake8
        args: ["--max-line-length=88", "--extend-ignore=E203,W503,E501"]
